// <auto-generated />
namespace AnalyzeFiles.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_row : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_row));
        
        string IMigrationMetadata.Id
        {
            get { return "202001072158598_add_row"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
